# Site settings
title: Nelspike's Blog
email: nelspiketx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Anything you can think about is here: Objects, theory and organization. Even cookies.
quote: >
  It's not a question of can or can't. There are some things in life you just do.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nelspike.github.io" # the base hostname & protocol for your site
twitter_username: nelspiketx
github_username:  Nelspike
poster: Nelson Oliveira

# Build settings
markdown: kramdown
highlighter: pygments
